### ISSUE TITLE
ATMega4808 support

### ISSUE THREAD

**Issue by neomonkey** [MCUdude/MajorCore#15]
Hi!

Is it possible to have a support for ATMega4808? I tried to understand what is done here, but I am too noob to edit these files. I can use ATMega1284, but it is quite large physically. 4808 is quite small with nice amount of SRAM.

Thanks.

**Comment by MCUdude** [comment]
Hi!
I have no plans of adding the new megaAVR microcontrollers. And if I'd ever do it, I'll most likely create a new separate core that supports both ATmega3208, ATmega4808, ATmega3209 and ATmega4809.

The problem is that these microcontrollers are fundamentally different than all existing AVRs. If you have the courage I'd definitly start by looking at the [official core files](https://github.com/arduino/ArduinoCore-megaavr) for the new Arduino UNO Wifi. It would require alot of work to make that happend. Maybe in the future 😉
